##https://jite.eu/2019/10/3/multi-arch-docker/

docker run --rm --privileged docker/binfmt:66f9012c56a8316f9244ffd7622d7c21c1f6f28d

docker buildx create --name my-new-builder --driver docker-container --us

docker buildx inspect --bootstrap

cd ./rtkbase/docker/cmd
docker buildx build --platform=linux/amd64,linux/arm64,linux/arm/v7 --push -t jancelin/centipede:cmd .

cd ./rtkbase/docker/rtklib
docker buildx build --platform=linux/amd64,linux/arm64,linux/arm/v7 --push -t jancelin/centipede:rtklib .

cd ./rtkbase/docker/receiver
docker buildx build --platform=linux/amd64,linux/arm64,linux/arm/v7 --push -t jancelin/centipede:receiver .
